{$if CompilerVersion >= 34.0}
{$define DX10_4}
{$define DX10_3}
{$define DX10_2}
{$define DX10_1}
{$define DX10}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_DX10_4_OR_LATER}
{$define DELPHI_DX10_3_OR_LATER}
{$define DELPHI_DX10_2_OR_LATER}
{$define DELPHI_DX10_1_OR_LATER}
{$define DELPHI_DX10_OR_LATER}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$ifend}

{$ifdef ver340}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver330}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver320}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver310}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver300}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver290}
{$define XE8}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE8_OR_LATER}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver280}
{$define XE7}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE7_OR_LATER}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver270}
{$define XE6}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE6_OR_LATER}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver260}
{$define XE5}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE5_OR_LATER}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver250}
{$define XE4}
{$define XE3}
{$define XE2}
{$define DELPHI_XE4_OR_LATER}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver240}
{$define XE3}
{$define XE2}
{$define DELPHI_XE3_OR_LATER}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver230}
{$define XE2}
{$define DELPHI_XE2_OR_LATER}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver220}
{$define DELPHI_XE_OR_LATER}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver210}
{$define DELPHI_2010_OR_LATER}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver200}
{$define DELPHI_2009_OR_LATER}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver195}
{$define DELPHI_2007_OR_LATER}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver190}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver180}
{$define DELPHI_2006_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_5_OR_LATER}
{$endif}

{$ifdef ver150}
{$define DELPHI_5_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_7_OR_LATER}
{$define DELPHI_7}
{$endif}

{$ifdef ver140}
{$define DELPHI_5_OR_LATER}
{$define DELPHI_6_OR_LATER}
{$define DELPHI_6}
{$endif}

{$ifdef ver130}
{$define DELPHI_5_OR_LATER}
{$define DELPHI_5}
{$endif}

//{$ifdef ver120}
//{$define DELPHI_2007_OR_LATER}
//{$define DELPHI_2006_OR_LATER}
//{$endif}

